name: SSH via Tailscale

on:
  workflow_dispatch:

jobs:
  secure-ssh:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Update & Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server curl

      - name: Configure SSH
        run: |
          # Enable and configure SSH
          sudo systemctl enable ssh
          sudo systemctl start ssh

          # Create SSH user with random secure password
          USERNAME="sshuser"
          PASSWORD=$(tr -dc 'A-Za-z0-9!@#$%&*' </dev/urandom | head -c 20)
          echo "$USERNAME:$PASSWORD" | sudo chpasswd
          sudo usermod -aG sudo $USERNAME

          echo "SSH_CREDS=User: $USERNAME | Password: $PASSWORD" >> $GITHUB_ENV

          # Allow password authentication
          sudo sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo sed -i 's/^#*PermitRootLogin.*/PermitRootLogin prohibit-password/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-${GITHUB_RUN_ID}

      - name: Fetch Tailscale IP
        run: |
          TS_IP=$(tailscale ip -4 | head -n1)
          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV

      - name: Verify SSH Accessibility
        run: |
          echo "Tailscale IP: $TAILSCALE_IP"
          nc -zv $TAILSCALE_IP 22

      - name: Maintain Connection
        run: |
          echo -e "\n=== SSH ACCESS ==="
          echo "Address: $TAILSCALE_IP"
          echo "Username: sshuser"
          echo "Password: $(echo $SSH_CREDS)"
          echo "==================\n"

          while true; do
            echo "[$(date)] SSH Active - Use Ctrl+C in workflow to terminate"
            sleep 300
          done
